# Flavours configuration

[[items]]
file = "~/.config/wezterm/base16_theme.lua"
template = "wezterm"
subtemplate = "lua"
rewrite = true
# hhok = wezterm watches the lua configuration !

[[items]]
file = "~/.config/nvim/lua/base16_colors.lua"
template = "luakit"
subtemplate = "colors"
rewrite = true
# hook: dynamic-base16.nvim watches the output file !

[[items]]
file = "~/.config/helix/themes/base16.toml"
template = "helix"
rewrite = true
# hook = not supported yet !

[[items]]
file = "~/.config/tmux/plugins/tmux/themes/catppuccin_base16.tmuxtheme"
template = "tmux"
rewrite = true
hook = "tmux source ~/.config/tmux/tmux.conf"

[[items]]
file = "~/.fzf_colors.zsh"
template = "fzf"
subtemplate = "base16-default"
rewrite = true
# hook = TODO: source this specific file again

[[items]]
file = "~/.config/spicetify/Themes/base16/color.ini"
template = "spicetify"
rewrite = true
hook = "spicetify refresh"

[[items]]
file = "~/.config/BetterDiscord/themes/base16.theme.css"
template = "betterdiscord"
rewrite = true
# hook = see the following item

[[items]]
file = "~/.config/BetterDiscord/data/stable/themes.json"
template = "betterdiscord"
subtemplate = "theme"
rewrite = true

[[items]]
file = "~/Notes/.obsidian/snippets/base16.css"
template = "obsidian"
rewrite = true
# hook = Obsidian watches css snippets !

[[items]]
file = "~/.config/zed/themes/base16.json"
template = "zed"
rewrite = true
# hook = zed watches user defined themes !

# Pywal compatibility (used for vscode theme)
[[items]]
file = "~/.cache/wal/colors"
template = "colors"
rewrite = true

[[items]]
file = "~/.cache/wal/colors.json"
template = "pywal"
rewrite = true
