# Flavours configuration

[[items]]
file = "~/.config/nvim/lua/base16_colors.lua"
template = "luakit"
subtemplate = "colors"
rewrite = true
# hook: dynamic-base16.nvim watches the output file !

[[items]]
file = "~/.config/helix/themes/base16.toml"
template = "helix"
rewrite = true
# hook = not supported yet !

[[items]]
file = "~/.config/tmux/plugins/tmux/themes/catppuccin_base16.tmuxtheme"
template = "tmux"
rewrite = true
hook = "tmux source ~/.config/tmux/tmux.conf"

[[items]]
file = "~/.fzf_colors.zsh"
template = "fzf"
subtemplate = "base16-default"
rewrite = true
# hook = TODO: source this specific file again

[[items]]
file = "~/.config/spicetify/Themes/base16/color.ini"
template = "spicetify"
rewrite = true
hook = "spicetify refresh"

[[items]]
file = "~/.config/BetterDiscord/themes/base16.theme.css"
template = "betterdiscord"
rewrite = true
# hook = BetterDiscord watches the css themes !

[[items]]
file = "~/Notes/.obsidian/snippets/base16.css"
template = "obsidian"
rewrite = true
# hook = Obsidian watches css snippets !

[[items]]
file = "~/.config/zed/themes/base16.json"
template = "zed"
rewrite = true
# hook = zed watches user defined themes !

[[items]]
file = "~/.config/Code/User/theme.json"
template = "vscode"
subtemplate = "base16"
rewrite = true
# hook = dynamic-base16-vscode extension watches the theme file !

[[items]]
file = "~/.config/zathura/colors.conf"
template = "zathura"
subtemplate = "recolor"
rewrite = true

[[items]]
file = "~/.mozilla/colors.toml"
template = "colors"
subtemplate = "toml"
rewrite = true
# hook = firefox-native-base16 watches the colors.toml file !

[[items]]
file = "~/.config/kitty/themes/base16.conf"
template = "kitty"
rewrite = true
hook = "kitten themes --reload-in=all base16"

[[items]]
file = "~/.config/hypr/colors.conf"
template = "hyprland"
rewrite = true
# hyprland watches the hypr/ folder !

[[items]]
file = "~/.config/rofi/colors.rasi"
template = "rofi"
subtemplate = "colors"
rewrite = true
