# Flavours configuration

[[items]]
file = "~/.config/wezterm/base16_theme.lua"
template = "wezterm"
subtemplate = "lua"
rewrite = true

[[items]]
file = "~/.config/nvim/lua/base16_colors.lua"
template = "luakit"
subtemplate = "colors"
rewrite = true
# hook: dynamic-base16.nvim watches the output file

[[items]]
file = "~/.config/helix/themes/base16.toml"
template = "helix"
rewrite = true
# hook = not supported yet !

[[items]]
file = "~/.config/tmux/plugins/tmux/themes/catppuccin_base16.tmuxtheme"
template = "tmux"
rewrite = true
hook = "tmux source ~/.config/tmux/tmux.conf"

[[items]]
file = "~/.fzf_colors.zsh"
template = "fzf"
subtemplate = "base16-default"
rewrite = true

[[items]]
# Pas satisfaisant non plus
file = "~/.config/Code/User/theme.json"
template = "vscode"
subtemplate = "base24"
rewrite = true

[[items]]
file = "~/.config/spicetify/Themes/base16/color.ini"
template = "spicetify"
rewrite = true
hook = "spicetify refresh"
