# Flavours configuration

[[items]]
file = "~/.config/wezterm/base16_theme.lua"
template = "wezterm"
subtemplate = "lua"
rewrite = true

[[items]]
file = "~/.config/nvim/lua/base16_colors.lua"
template = "luakit"
subtemplate = "colors"
rewrite = true
hook = "nvim-reload-scheme"

[[items]]
file = "~/.config/helix/themes/base16.toml"
template = "helix"
rewrite = true
# hook = not supported yet !
